
echo "<div class='monitor_title'>${TITLE}</div>"

local sep="</tr><tr>"
[ ${COLUMNS} -gt 1 ] && sep=""

echo "<table>"
echo "<tr>"
echo "<td>"
echo "<div class='monitor_title'>Available RAM:</div>"
echo "<div>${RAM_FREE_GB}/${RAM_TOT_GB}Gb</div>"
echo "<div>"
echo "<span>${RAM_FREE_PERC}%</span>"
echo "<span class='${RAM_CLASS}'><span>"
echo "</div>"
echo "</td>"
echo $sep
echo "<td>"
echo "<div class='monitor_title'>Unused SWAP:</div>"
echo "<div>${SWAP_FREE_GB}/${SWAP_TOT_GB}Gb</div>"
echo "<div>"
echo "<span>${SWAP_FREE_PERC}%</span>"
echo "<span class='${SWAP_CLASS}'><span>"
echo "</div>"
echo "</td>"
echo "</tr>"
echo "</table>"
